//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding_yungching
{
    using System;
    using System.Collections.Generic;
    
    public partial class Happy_time_drink
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string DrinkName { get; set; }
        public string DrinkSweet { get; set; }
        public string DrinkIce { get; set; }
        public string DrinkSize { get; set; }
        public string DrinkAmount { get; set; }
        public Nullable<double> DrinkHowMatch { get; set; }
        public string Date { get; set; }
        public string Pay { get; set; }
        public string Paytype { get; set; }
        public Nullable<double> Paymoney { get; set; }
        public string State { get; set; }
    }
}
