//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding_yungching
{
    using System;
    using System.Collections.Generic;
    
    public partial class HKuser
    {
        public int id { get; set; }
        public string name { get; set; }
        public string clock_id { get; set; }
        public string numberid { get; set; }
        public string startday { get; set; }
        public string title { get; set; }
        public string department { get; set; }
        public string adaccount { get; set; }
        public string LeaveAll { get; set; }
        public Nullable<int> state { get; set; }
        public string RightIds { get; set; }
        public Nullable<double> Balance { get; set; }
    }
}
