//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding_yungching
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRequest_Role
    {
        public int id { get; set; }
        public string Company { get; set; }
        public string Program { get; set; }
        public string Name { get; set; }
        public string Account { get; set; }
        public Nullable<int> Number { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}
