//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding_yungching
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SDpay : DbContext
    {
        public SDpay()
            : base("name=SDPay")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clock> clock { get; set; }
        public virtual DbSet<Happy_time_drink> Happy_time_drink { get; set; }
        public virtual DbSet<Happy_time_food> Happy_time_food { get; set; }
        public virtual DbSet<HKuser> HKuser { get; set; }
        public virtual DbSet<Leave> Leave { get; set; }
        public virtual DbSet<LeaveRequest> LeaveRequest { get; set; }
        public virtual DbSet<LeaveRequest_Role> LeaveRequest_Role { get; set; }
        public virtual DbSet<Movie> Movie { get; set; }
        public virtual DbSet<report_clock> report_clock { get; set; }
        public virtual DbSet<SDhappytime> SDhappytime { get; set; }
        public virtual DbSet<SDLeave_Year> SDLeave_Year { get; set; }
        public virtual DbSet<SDMisPs> SDMisPs { get; set; }
        public virtual DbSet<SDuser> SDuser { get; set; }
        public virtual DbSet<test> test { get; set; }
        public virtual DbSet<Uploadinfo> Uploadinfo { get; set; }
        public virtual DbSet<Wedding_Question> Wedding_Question { get; set; }
        public virtual DbSet<Wedding_UserAns> Wedding_UserAns { get; set; }
        public virtual DbSet<Wedding_UserInfo> Wedding_UserInfo { get; set; }
        public virtual DbSet<workadd> workadd { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
    }
}
