//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding_yungching
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_clock
    {
        public int id { get; set; }
        public string clock_id { get; set; }
        public string name { get; set; }
        public string date { get; set; }
        public string week { get; set; }
        public string rclock_in { get; set; }
        public string rclock_out { get; set; }
        public string state { get; set; }
        public string leave { get; set; }
        public string account { get; set; }
        public string Ex { get; set; }
    }
}
