//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding_yungching
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDhappytime
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string DrinkName { get; set; }
        public string DrinkSweet { get; set; }
        public string DrinkIce { get; set; }
        public string DrinkSize { get; set; }
        public string DrinkAmount { get; set; }
        public string DrinkHowMatch { get; set; }
        public string Food01Name { get; set; }
        public string Food01Taste { get; set; }
        public string Food01QA01 { get; set; }
        public string Food01Amount { get; set; }
        public string Food01HM { get; set; }
        public string Date { get; set; }
        public string pay { get; set; }
        public string account { get; set; }
        public string paytype { get; set; }
        public Nullable<double> paymoney { get; set; }
        public string state { get; set; }
    }
}
