//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding_yungching
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wedding_UserAns
    {
        public int id { get; set; }
        public string weddingname { get; set; }
        public string uid { get; set; }
        public string name { get; set; }
        public int ans { get; set; }
        public string XorV { get; set; }
        public Nullable<double> fraction { get; set; }
        public Nullable<System.DateTime> anstime { get; set; }
    }
}
