//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding_yungching
{
    using System;
    using System.Collections.Generic;
    
    public partial class workadd
    {
        public int id { get; set; }
        public string name { get; set; }
        public string date { get; set; }
        public string starttime { get; set; }
        public string endtime { get; set; }
        public string wkind { get; set; }
        public Nullable<double> hour { get; set; }
        public string Ex { get; set; }
        public string Orderid { get; set; }
    }
}
